<<<<<<< HEAD
# Generated by Django 5.2.3 on 2025-06-30 09:38
=======
# Generated by Django 5.2.3 on 2025-06-30 05:02
>>>>>>> ae066601e81b303a82bfd355d29c0407101ec3c3

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='image',
<<<<<<< HEAD
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
=======
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='image'),
>>>>>>> ae066601e81b303a82bfd355d29c0407101ec3c3
        ),
    ]
