# Generated by Django 5.2.3 on 2025-06-30 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_blog_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('roll_number', models.CharField(max_length=20, unique=True)),
                ('mobile', models.CharField(max_length=15, unique=True)),
            ],
        ),
    ]
